# -*- coding: utf-8 -*-
"""only_create_tuples.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Kh4pdTUfOTTtWy6u2dpy3o1zpfmPLqN6
"""

# CREATE THE TUPLES 

copy= text_in_numbers

'''
# for checking purpose shorter list 
text_in_numbers = [0, 1, 2, 3, 4]
'''

word_pairs = list()

window_size = 4

# go through text
for i in range(len(text_in_numbers)):

  # depending on window size only create tuples with elements in the list (only if j>=0 and j<len(text))
  for j in range(1,int(window_size/2 +1)): # only works for even numbers as window_size
    if i-j>=0:
      word_pairs.append((np.int64(text_in_numbers[i]), np.int64(text_in_numbers[i-j])))
    if i+j<len(text_in_numbers):
      word_pairs.append((np.int64(text_in_numbers[i]), np.int64(text_in_numbers[i+j])))


# convert tuples to a tf dataset
data = tf.data.Dataset.from_tensor_slices(word_pairs)

'''
# look at tensors to check
for elem in data:
  print(elem.numpy())
'''

# shuffle, batch and prefetch (do we need prefetch?)
data = data.shuffle(10000).batch(64).prefetch(tf.data.AUTOTUNE)